name: Build Kivy App
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Compilar con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master
      - name: Descargar artefacto
        uses: actions/upload-artifact@v3
        with:
          name: PuntoMAX-APK
          path: ${{ steps.buildozer.outputs.filename }}
